site_name: Antenna FAQ
pages:

- Introduction: 'index.md'
- Devices and Installing: 'devices.md'
- Base App: 'baseapp.md'
- App Submission: 'submission.md'
- Publisher: 'publisher.md'
- Reveal: 'reavealblock.md'
- Cloud and Data Collections: 'CloudCollectionsandData.md'
- Assets: 'assets.md'
- DM Tools:
    - 'Jira': 'dmtools/jira.md'
    - 'Smarthseet': 'dmtools/smartsheet.md'
    - 'Useful Links': 'dmtools/useful.md'
- QA: 'qa.md'
- How to make edits: 'editing_how_to.md'
theme: null
theme_dir: 'antenna_material'
extra_css: [extra.css]
# theme: spacelab
# theme: material
# theme: slate
# theme: journal
# theme: flatly
# theme: cyborg
# theme: cosmo
# theme: cerulean
# theme: simplex
# theme: united
# theme: readable
# theme: yeti
