#site_name: Antenna FAQ
pages:

- Good Day: 'index.md'
- Devices and Installing: 'devices.md'
- Base App: 'baseapp.md'
- Components:
    - 'Media Slider / Progressbar': 'components/mediaslider.md'
- App Submission: 'submission.md'
- Publisher: 'publisher.md'
- Reveal: 'reavealblock.md'
- Cloud and Data Collections: 'CloudCollectionsandData.md'
- Assets: 'assets.md'
- DM Tools:
    - 'Jira': 'dmtools/jira.md'
    - 'Smarthseet': 'dmtools/smartsheet.md'
    - 'Useful Links': 'dmtools/useful.md'
- QA: 'qa.md'
- Compilers:
    - 'Virtual Compiler': 'compilers/virtualcompiler.md'
    - 'Legacy Compilers': 'compilers/legacy.md'
    - 'XP-2': 'compilers/xp2.md'
    - 'XPC to XP-2': 'compilers/compilersxpctoxp2.md'
    - 'Wand': 'compilers/wand.md'
- How to:
  - 'Make edits to this FAQ': 'how-to/editing_how_to.md'
  - 'Inspect Webviews in Apps': 'how-to/inspectWebviews.md'
theme: null
theme_dir: 'antenna_material'

extra_css: [extra.css]
extra_javascript: [scripts.js]
# theme: spacelab
# theme: material
# theme: slate
# theme: journal
# theme: flatly
# theme: cyborg
# theme: cosmo
# theme: cerulean
# theme: simplex
# theme: united
# theme: readable
# theme: yeti
